BTW Project Euler problem 2
BTW Find the sum of all the even Fibonacci numbers below 4,000,000
HAI 1.2
I HAS A FIB ITZ 1
I HAS A TOTAL ITZ 0
IM IN YR LOOP UPPIN YR NUM WILE DIFFRINT FIB AN BIGGR OF FIB AN 4000000
  DIFFRINT NUM AN 0
  O RLY?
    YA RLY
      FIB R PRODUKT OF FIB AN NUM
      BOTH SAEM MOD OF FIB AN 2 AN 0
      O RLY?
        YA RLY
          TOTAL R SUM OF TOTAL AN FIB
      OIC
  OIC
IM OUTTA YR LOOP
VISIBLE TOTAL
KTHXBYE
