BTW Project Euler problem 1
BTW Find the sum of all multiples of 3 and 5 below 1000
HAI 1.2
I HAS A TOTAL ITZ 0
IM IN YR LOOP UPPIN YR NUM WILE DIFFRINT NUM AN 1000
  EITHER OF BOTH SAEM MOD OF NUM AN 3 AN 0 AN BOTH SAEM MOD OF NUM AN 5 AN 0
  O RLY?
    YA RLY
      TOTAL R SUM OF TOTAL AN NUM
  OIC
IM OUTTA YR LOOP
VISIBLE TOTAL
KTHXBYE
